### ISSUE TITLE
Is there any way to highlight syntax in HTML?

### ISSUE THREAD

**Issue by JJBocanegra** [karingisi/syntaxed#2]
I want to see it like the first HTML block of code but I can't make it work. Could you explain it a little more in the README?
![Image](http://i.imgur.com/xDeIf7Y.png)

Thanks.

**Comment by karingisi** [comment]
Hi JJBocanegra,
Thank you for taking time to download and use my plugin. 
The behaviour that you are seeing as per above image is absolutely correct. Prism when you use a language-html it does not highlight the actual syntax rather highlights what is outputted by the html code. In your example it does not have any output. If you had put for example. <p> Syntax is awesome</p>. You would have seen "Syntax is awesome".

To Achieve what you want you need to use  language-markup instead of language-html.
example:

<pre class=" language-markup"><code class=" language-markup"><span class="token doctype">&lt;!DOCTYPE html&gt;</span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>html</span><span class="token punctuation">&gt;</span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>html</span><span class="token punctuation">&gt;</span></span></code></pre>

For more examples please check http://prismjs.com/examples.html  
Just right click to inspect element on examples.
I hope this is helpful. Cheers
